// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHxi8EnTTEItP7Q0qWTov-tsgvBNh9oTQ',
    appId: '1:810384818384:web:2c009e601568f37d4c1ed5',
    messagingSenderId: '810384818384',
    projectId: 'babycare-18f40',
    authDomain: 'babycare-18f40.firebaseapp.com',
    storageBucket: 'babycare-18f40.firebasestorage.app',
    measurementId: 'G-RV12HVVG7V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEN49ajQVdr92sK-mk68abuGYEWFHNVjU',
    appId: '1:810384818384:android:1f758dae72af67f34c1ed5',
    messagingSenderId: '810384818384',
    projectId: 'babycare-18f40',
    storageBucket: 'babycare-18f40.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABixrbm4nqESj3J-ns8IZVb_iE29s1A4k',
    appId: '1:810384818384:ios:9714d6556afcde734c1ed5',
    messagingSenderId: '810384818384',
    projectId: 'babycare-18f40',
    storageBucket: 'babycare-18f40.firebasestorage.app',
    iosClientId: '810384818384-ovj5em2lhrtvjf9fg1tcen57lp8567k6.apps.googleusercontent.com',
    iosBundleId: 'com.babycare.babycaree',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABixrbm4nqESj3J-ns8IZVb_iE29s1A4k',
    appId: '1:810384818384:ios:9714d6556afcde734c1ed5',
    messagingSenderId: '810384818384',
    projectId: 'babycare-18f40',
    storageBucket: 'babycare-18f40.firebasestorage.app',
    iosClientId: '810384818384-ovj5em2lhrtvjf9fg1tcen57lp8567k6.apps.googleusercontent.com',
    iosBundleId: 'com.babycare.babycaree',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHxi8EnTTEItP7Q0qWTov-tsgvBNh9oTQ',
    appId: '1:810384818384:web:45feafa675ba62554c1ed5',
    messagingSenderId: '810384818384',
    projectId: 'babycare-18f40',
    authDomain: 'babycare-18f40.firebaseapp.com',
    storageBucket: 'babycare-18f40.firebasestorage.app',
    measurementId: 'G-RY4MLX1Y8N',
  );
}
